#!/bin/bash
set -e

USER_ID=${USER_ID:-$(id -u)}
GROUP_ID=${GROUP_ID:-$(id -g)}
USERNAME=${USERNAME:-'dev'}
GROUPNAME=${GROUPNAME:-'dev'}
HOMEDIR=${HOMEDIR:-"/home/$USERNAME"}

make dkc-env

docker-compose run --rm \
-e USER_ID=$USER_ID \
-e GROUP_ID=$GROUP_ID \
-e USERNAME=$USERNAME \
-e GROUPNAME=$GROUPNAME \
-e HOMEDIR=$HOMEDIR \
-e SSH_PRIVATE_KEY="$SSH_PRIVATE_KEY" \
-e SSH_PUBLIC_KEY="$SSH_PUBLIC_KEY" \
python bash
